name: Dart Format CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify formatting (monorepo)
        run: dart format --output=none --set-exit-if-changed .
