name: Dart Functions CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: openci-org/flutter-setup@v1
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: cd firebase/dart_functions && flutter pub get

      - name: Analyze
        run: cd firebase/dart_functions && flutter analyze

      - name: Test
        run: cd firebase/dart_functions && flutter test
