name: Demo Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./actions/flutter
        with:
          working-directory: "apps/dashboard"
          analyze: "true"
          test: "true"
