name: Demo Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    steps:
      - name: 
        uses: actions/checkout@v4
      - name: Install dependencies
        run: flutter pub get
