name: Flutter Dashboard CI/CD (iOS & Web)

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openci-org/flutter-setup@v1
        with:
          flutter-version: "stable"
      - uses: openci-org/save-secret-file@v1
        with:
          secret: ${{ secrets.FIREBASE_OPTIONS }}
          path: "apps/dashboard/lib/firebase_options.dart"
      - uses: openci-org/flutter-ci@v1
        with:
          test: "false"
          working-directory: "apps/dashboard"

  deploy-ios:
    needs: [ci]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openci-org/flutter-setup@v1
        with:
          flutter-version: "stable"
      - uses: openci-org/save-secret-file@v1
        with:
          secret: ${{ secrets.FIREBASE_OPTIONS }}
          path: "apps/dashboard/lib/firebase_options.dart"
      - uses: openci-org/save-secret-file@v1
        with:
          secret: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_IOS }}
          path: "apps/dashboard/ios/Runner/GoogleService-Info.plist"
      - uses: openci-org/flutter-cd@v2
        with:
          platform: "ios"
          working-directory: "apps/dashboard"
          build-number: ${{ env.OPENCI_RUN_NUMBER }}
          build-args: "--dart-define=REVENUE_CAT_API_KEY=${{ secrets.REVENUE_CAT_API_KEY }}"
          certificate-private-key: ${{ secrets.OPENCI_CERTIFICATE_PRIVATE_KEY }}
          asc-key-id: ${{ secrets.OPENCI_ASC_KEY_ID }}
          asc-issuer-id: ${{ secrets.OPENCI_ASC_ISSUER_ID }}
          asc-private-key: ${{ secrets.OPENCI_ASC_PRIVATE_KEY }}

  deploy-web:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: openci-org/flutter-setup@v1
        with:
          flutter-version: "stable"
      - uses: openci-org/save-secret-file@v1
        with:
          secret: ${{ secrets.FIREBASE_OPTIONS }}
          path: "apps/dashboard/lib/firebase_options.dart"
      - uses: openci-org/flutter-cd@v2
        with:
          platform: "web"
          working-directory: "apps/dashboard"
          build-number: ${{ env.OPENCI_RUN_NUMBER }}
          build-args: "--dart-define=REVENUE_CAT_API_KEY=${{ secrets.REVENUE_CAT_API_KEY }} --dart-define=REVENUE_CAT_WEB_API_KEY=${{ secrets.REVENUE_CAT_WEB_API_KEY }}"
          firebase-service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
