name: Functions Dart CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: firebase/functions_dart

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Analyze
        run: flutter analyze
