name: macOS Updater CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

defaults:
  run:
    working-directory: packages/macos_updater

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test
