name: openci_server CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Analyze openci_server
        run: flutter analyze apps/openci_server

      - name: Run Tests (openci_server)
        run: flutter test apps/openci_server
