name: Test Flutter Setup

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: open-ci-io/flutter-setup@v1
        with:
          flutter-version: "stable"

      - name: Save firebase_options.dart
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 -D > apps/dashboard/lib/firebase_options.dart

      - uses: open-ci-io/flutter-ci@v1
        with:
          test: "false"
          working-directory: "apps/dashboard"
