import 'dart:io';

import 'package:hooks/hooks.dart';

/// Automatically syncs the version defined in `pubspec.yaml` to a Dart source file.
///
/// Reads the version string from `pubspec.yaml` in the package root, writes it to
/// the target file (defaults to `lib/src/version.dart`), and adds `pubspec.yaml`
/// to the [BuildOutput.dependencies] list to ensure the build hook is re-run
/// whenever `pubspec.yaml` changes.
Future<void> syncPubspecVersion(
  BuildInput input,
  BuildOutputBuilder output, {
  String outputRelativePath = 'lib/src/version.dart',
  String variableName = 'packageVersion',
}) async {
  await syncVersionCore(
    packageRoot: Directory.fromUri(input.packageRoot),
    outputRelativePath: outputRelativePath,
    variableName: variableName,
    registerDependency: (uri) => output.dependencies.add(uri),
  );
}

/// Core version syncing logic extracted for testability.
///
/// This is exposed for unit testing purposes.
Future<void> syncVersionCore({
  required Directory packageRoot,
  required String outputRelativePath,
  required String variableName,
  required void Function(Uri uri) registerDependency,
}) async {
  // Resolve path to pubspec.yaml
  final pubspecFile = File('${packageRoot.path}/pubspec.yaml');

  if (!await pubspecFile.exists()) {
    throw Exception('pubspec.yaml not found at ${pubspecFile.path}');
  }

  // Register pubspec.yaml as a build dependency
  registerDependency(pubspecFile.uri);

  // Extract the version string
  final lines = await pubspecFile.readAsLines();
  String? version;
  for (final line in lines) {
    if (line.startsWith('version:')) {
      version = line.replaceFirst('version:', '').trim();
      break;
    }
  }

  if (version == null) {
    throw Exception('version field not found in pubspec.yaml');
  }

  // Resolve path to output version file
  final versionFile = File('${packageRoot.path}/$outputRelativePath');

  // Ensure parent directory exists
  final versionDir = versionFile.parent;
  if (!await versionDir.exists()) {
    await versionDir.create(recursive: true);
  }

  // Write out version file contents
  final content = '''
// Generated by pubspec_version_hook. Do not edit.
const $variableName = '$version';
''';

  await versionFile.writeAsString(content);
}
