// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'repository.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Repository _$RepositoryFromJson(Map<String, dynamic> json) => _Repository(
  forksUrl: json['forks_url'] as String?,
  assigneesUrl: json['assignees_url'] as String?,
  blobsUrl: json['blobs_url'] as String?,
  branchesUrl: json['branches_url'] as String?,
  collaboratorsUrl: json['collaborators_url'] as String?,
  commentsUrl: json['comments_url'] as String?,
  commitsUrl: json['commits_url'] as String?,
  compareUrl: json['compare_url'] as String?,
  contentsUrl: json['contents_url'] as String?,
  contributorsUrl: json['contributors_url'] as String?,
  deploymentsUrl: json['deployments_url'] as String?,
  description: json['description'],
  downloadsUrl: json['downloads_url'] as String?,
  eventsUrl: json['events_url'] as String?,
  fork: json['fork'] as bool?,
  archiveUrl: json['archive_url'] as String?,
  fullName: json['full_name'] as String?,
  gitCommitsUrl: json['git_commits_url'] as String?,
  gitRefsUrl: json['git_refs_url'] as String?,
  gitTagsUrl: json['git_tags_url'] as String?,
  hooksUrl: json['hooks_url'] as String?,
  htmlUrl: json['html_url'] as String?,
  id: (json['id'] as num?)?.toInt(),
  issueCommentUrl: json['issue_comment_url'] as String?,
  issueEventsUrl: json['issue_events_url'] as String?,
  issuesUrl: json['issues_url'] as String?,
  keysUrl: json['keys_url'] as String?,
  labelsUrl: json['labels_url'] as String?,
  languagesUrl: json['languages_url'] as String?,
  url: json['url'] as String?,
  milestonesUrl: json['milestones_url'] as String?,
  name: json['name'] as String?,
  nodeId: json['node_id'] as String?,
  notificationsUrl: json['notifications_url'] as String?,
  owner: json['owner'] == null
      ? null
      : Owner13.fromJson(json['owner'] as Map<String, dynamic>),
  private: json['private'] as bool?,
  pullsUrl: json['pulls_url'] as String?,
  releasesUrl: json['releases_url'] as String?,
  stargazersUrl: json['stargazers_url'] as String?,
  statusesUrl: json['statuses_url'] as String?,
  subscribersUrl: json['subscribers_url'] as String?,
  subscriptionUrl: json['subscription_url'] as String?,
  tagsUrl: json['tags_url'] as String?,
  teamsUrl: json['teams_url'] as String?,
  treesUrl: json['trees_url'] as String?,
  mergesUrl: json['merges_url'] as String?,
);

Map<String, dynamic> _$RepositoryToJson(_Repository instance) =>
    <String, dynamic>{
      'forks_url': instance.forksUrl,
      'assignees_url': instance.assigneesUrl,
      'blobs_url': instance.blobsUrl,
      'branches_url': instance.branchesUrl,
      'collaborators_url': instance.collaboratorsUrl,
      'comments_url': instance.commentsUrl,
      'commits_url': instance.commitsUrl,
      'compare_url': instance.compareUrl,
      'contents_url': instance.contentsUrl,
      'contributors_url': instance.contributorsUrl,
      'deployments_url': instance.deploymentsUrl,
      'description': instance.description,
      'downloads_url': instance.downloadsUrl,
      'events_url': instance.eventsUrl,
      'fork': instance.fork,
      'archive_url': instance.archiveUrl,
      'full_name': instance.fullName,
      'git_commits_url': instance.gitCommitsUrl,
      'git_refs_url': instance.gitRefsUrl,
      'git_tags_url': instance.gitTagsUrl,
      'hooks_url': instance.hooksUrl,
      'html_url': instance.htmlUrl,
      'id': instance.id,
      'issue_comment_url': instance.issueCommentUrl,
      'issue_events_url': instance.issueEventsUrl,
      'issues_url': instance.issuesUrl,
      'keys_url': instance.keysUrl,
      'labels_url': instance.labelsUrl,
      'languages_url': instance.languagesUrl,
      'url': instance.url,
      'milestones_url': instance.milestonesUrl,
      'name': instance.name,
      'node_id': instance.nodeId,
      'notifications_url': instance.notificationsUrl,
      'owner': instance.owner,
      'private': instance.private,
      'pulls_url': instance.pullsUrl,
      'releases_url': instance.releasesUrl,
      'stargazers_url': instance.stargazersUrl,
      'statuses_url': instance.statusesUrl,
      'subscribers_url': instance.subscribersUrl,
      'subscription_url': instance.subscriptionUrl,
      'tags_url': instance.tagsUrl,
      'teams_url': instance.teamsUrl,
      'trees_url': instance.treesUrl,
      'merges_url': instance.mergesUrl,
    };
