name: dart_functions
description: An app using Firebase Functions for Dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.4.0
  dio: ^5.9.0
  firebase_functions: ^0.5.0
  github_client:
    path: ../../packages/github_client
  google_cloud_secretmanager_v1: ^0.5.0
  googleapis_auth: ^2.3.0
  sentry: ^9.1.0
  sentry_dio: ^9.1.0
  shelf: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.25.0
