// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by OpenCI CLI (`openci sync paths`)
// dart format off

import 'package:openci_workflow/openci_workflow.dart' show WorkspaceDirectory;

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const root = WorkspaceRoot._('.');
}

extension type const WorkspaceRoot._(String _path) implements WorkspaceDirectory {
  WorkspaceRoot$Apps get apps => const WorkspaceRoot$Apps._("apps");
  WorkspaceDirectory get openci => const WorkspaceDirectory("openci");
  WorkspaceRoot$Packages get packages => const WorkspaceRoot$Packages._("packages");
}

extension type const WorkspaceRoot$Apps._(String _path) implements WorkspaceDirectory {
  WorkspaceRoot$Apps$BuildJobPlanner get buildJobPlanner => const WorkspaceRoot$Apps$BuildJobPlanner._("apps/build_job_planner");
  WorkspaceRoot$Apps$BuildJobWorker get buildJobWorker => const WorkspaceRoot$Apps$BuildJobWorker._("apps/build_job_worker");
  WorkspaceRoot$Apps$Dashboard get dashboard => const WorkspaceRoot$Apps$Dashboard._("apps/dashboard");
  WorkspaceRoot$Apps$GenuineciServer get genuineciServer => const WorkspaceRoot$Apps$GenuineciServer._("apps/genuineci_server");
  WorkspaceRoot$Apps$OpenciCli get openciCli => const WorkspaceRoot$Apps$OpenciCli._("apps/openci_cli");
}

extension type const WorkspaceRoot$Apps$BuildJobPlanner._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get bin => const WorkspaceDirectory("apps/build_job_planner/bin");
  WorkspaceDirectory get lib => const WorkspaceDirectory("apps/build_job_planner/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("apps/build_job_planner/test");
}

extension type const WorkspaceRoot$Apps$BuildJobWorker._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get bin => const WorkspaceDirectory("apps/build_job_worker/bin");
  WorkspaceDirectory get lib => const WorkspaceDirectory("apps/build_job_worker/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("apps/build_job_worker/test");
}

extension type const WorkspaceRoot$Apps$Dashboard._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get android => const WorkspaceDirectory("apps/dashboard/android");
  WorkspaceDirectory get assets => const WorkspaceDirectory("apps/dashboard/assets");
  WorkspaceDirectory get ios => const WorkspaceDirectory("apps/dashboard/ios");
  WorkspaceDirectory get lib => const WorkspaceDirectory("apps/dashboard/lib");
  WorkspaceDirectory get macos => const WorkspaceDirectory("apps/dashboard/macos");
  WorkspaceDirectory get scripts => const WorkspaceDirectory("apps/dashboard/scripts");
  WorkspaceDirectory get test => const WorkspaceDirectory("apps/dashboard/test");
  WorkspaceDirectory get web => const WorkspaceDirectory("apps/dashboard/web");
}

extension type const WorkspaceRoot$Apps$GenuineciServer._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get integrationTest => const WorkspaceDirectory("apps/genuineci_server/integration_test");
  WorkspaceDirectory get lib => const WorkspaceDirectory("apps/genuineci_server/lib");
  WorkspaceDirectory get routes => const WorkspaceDirectory("apps/genuineci_server/routes");
  WorkspaceDirectory get test => const WorkspaceDirectory("apps/genuineci_server/test");
}

extension type const WorkspaceRoot$Apps$OpenciCli._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get bin => const WorkspaceDirectory("apps/openci_cli/bin");
  WorkspaceDirectory get lib => const WorkspaceDirectory("apps/openci_cli/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("apps/openci_cli/test");
}

extension type const WorkspaceRoot$Packages._(String _path) implements WorkspaceDirectory {
  WorkspaceRoot$Packages$MacosUpdater get macosUpdater => const WorkspaceRoot$Packages$MacosUpdater._("packages/macos_updater");
  WorkspaceRoot$Packages$OpenciShared get openciShared => const WorkspaceRoot$Packages$OpenciShared._("packages/openci_shared");
  WorkspaceRoot$Packages$OpenciWorkflow get openciWorkflow => const WorkspaceRoot$Packages$OpenciWorkflow._("packages/openci_workflow");
  WorkspaceRoot$Packages$PubspecVersionHook get pubspecVersionHook => const WorkspaceRoot$Packages$PubspecVersionHook._("packages/pubspec_version_hook");
}

extension type const WorkspaceRoot$Packages$MacosUpdater._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get example => const WorkspaceDirectory("packages/macos_updater/example");
  WorkspaceDirectory get lib => const WorkspaceDirectory("packages/macos_updater/lib");
  WorkspaceDirectory get macos => const WorkspaceDirectory("packages/macos_updater/macos");
  WorkspaceDirectory get pigeons => const WorkspaceDirectory("packages/macos_updater/pigeons");
  WorkspaceDirectory get test => const WorkspaceDirectory("packages/macos_updater/test");
}

extension type const WorkspaceRoot$Packages$OpenciShared._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get lib => const WorkspaceDirectory("packages/openci_shared/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("packages/openci_shared/test");
}

extension type const WorkspaceRoot$Packages$OpenciWorkflow._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get lib => const WorkspaceDirectory("packages/openci_workflow/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("packages/openci_workflow/test");
}

extension type const WorkspaceRoot$Packages$PubspecVersionHook._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get lib => const WorkspaceDirectory("packages/pubspec_version_hook/lib");
  WorkspaceDirectory get test => const WorkspaceDirectory("packages/pubspec_version_hook/test");
}
