// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by OpenCI CLI (`openci sync secrets`)
// dart format off

import 'dart:io';

/// Provides type-safe access to OpenCI secrets via environment variables.
abstract final class Secrets {
  /// Secret key: `FIREBASE_OPTIONS_DART_BASE64`
  static String get firebaseOptionsDartBase64 =>
      Platform.environment['FIREBASE_OPTIONS_DART_BASE64'] ??
      (throw StateError("Secret 'FIREBASE_OPTIONS_DART_BASE64' is not set in environment."));

  /// Secret key: `GOOGLE_SERVICES_JSON_BASE64`
  static String get googleServicesJsonBase64 =>
      Platform.environment['GOOGLE_SERVICES_JSON_BASE64'] ??
      (throw StateError("Secret 'GOOGLE_SERVICES_JSON_BASE64' is not set in environment."));
}
