analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/build/**"
    - "**/node_modules/**"
    - "web/**"
    - "worker/**"
    - "firebase/**"

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    unawaited_futures: true

formatter:
  trailing_commas: preserve

