name: openci
publish_to: none

environment:
  sdk: 3.11.5

workspace:
  - apps/dashboard
  - apps/openci_build_job_processor
  - apps/openci_build_job_processor_linux
  - apps/openci_server
  - apps/openci_worker_cli
  - packages/app_minimizer_plus
  - packages/app_minimizer_plus/example
  - packages/lume_dart
  - packages/macos_updater
  - packages/openci_shared
  - packages/openci_job_processor_shared
  - packages/pubspec_version_hook

dependency_overrides:
  analyzer: 10.0.1
  dart_style: 3.1.7
