name: openci
publish_to: none

environment:
  sdk: 3.11.5

workspace:
  - apps/dashboard
  - firebase/functions_dart
  - packages/macos_updater
  - packages/openci_shared
  - packages/app_minimizer_plus
  - packages/app_minimizer_plus/example
  - packages/gcp_secret_manager
  - apps/openci_worker_cli
  - packages/avf_dart


dependency_overrides:
  analyzer: 9.0.0
