// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class AppMinimizerApiPigeonCodecReader: FlutterStandardReader {
}

private class AppMinimizerApiPigeonCodecWriter: FlutterStandardWriter {
}

private class AppMinimizerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return AppMinimizerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return AppMinimizerApiPigeonCodecWriter(data: data)
  }
}

class AppMinimizerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = AppMinimizerApiPigeonCodec(readerWriter: AppMinimizerApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppMinimizerHostApi {
  func minimize() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppMinimizerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { AppMinimizerApiPigeonCodec.shared }
  /// Sets up an instance of `AppMinimizerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppMinimizerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let minimizeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.app_minimizer_plus.AppMinimizerHostApi.minimize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      minimizeChannel.setMessageHandler { _, reply in
        do {
          try api.minimize()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      minimizeChannel.setMessageHandler(nil)
    }
  }
}
