// File generated by FlutterFire configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => macos,
      TargetPlatform.windows => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows.',
      ),
      TargetPlatform.linux => throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux.',
      ),
      _ => throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      ),
    };
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXVu-HSAUm1EjExgKjEzvtdSWJmDNy_Qs',
    appId: '1:957653597519:web:e4adc394d921b64eca593a',
    messagingSenderId: '957653597519',
    projectId: 'ima-release',
    authDomain: 'ima-release.firebaseapp.com',
    storageBucket: 'ima-release.firebasestorage.app',
    measurementId: 'G-Q6658C85HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzOMZ-0dlVKYm2fP9W4iwvomOUSTZpZNI',
    appId: '1:957653597519:android:d194d98ea5136d88ca593a',
    messagingSenderId: '957653597519',
    projectId: 'ima-release',
    storageBucket: 'ima-release.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1PmJH59msN_CotqndtGtDU-yPluptPw',
    appId: '1:957653597519:ios:f614d8e5ffe917d4ca593a',
    messagingSenderId: '957653597519',
    projectId: 'ima-release',
    storageBucket: 'ima-release.firebasestorage.app',
    iosBundleId: 'org.openci.ima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1PmJH59msN_CotqndtGtDU-yPluptPw',
    appId: '1:957653597519:ios:b02d686a33c122eaca593a',
    messagingSenderId: '957653597519',
    projectId: 'ima-release',
    storageBucket: 'ima-release.firebasestorage.app',
    iosBundleId: 'org.openci.ima.macos',
  );
}
