// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync secrets`)
// dart format off

import 'dart:io';

/// Provides type-safe access to Genuine CI secrets via environment variables.
abstract final class Secrets {
  /// Secret key: `FIREBASE_OPTIONS_DART_BASE64`
  static String get firebaseOptionsDartBase64 =>
      Platform.environment['FIREBASE_OPTIONS_DART_BASE64'] ??
      (throw StateError("Secret 'FIREBASE_OPTIONS_DART_BASE64' is not set in environment."));

  /// Secret key: `TEST`
  static String get test =>
      Platform.environment['TEST'] ??
      (throw StateError("Secret 'TEST' is not set in environment."));
}
