// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync secrets`)

import 'dart:io';

/// Provides type-safe access to Genuine CI secrets via environment variables.
abstract final class Secrets {
  const Secrets._();

  /// Secret key: `ASC_KEY`
  static String get ascKey =>
      Platform.environment['ASC_KEY'] ??
      (throw StateError("Secret 'ASC_KEY' is not set in environment."));

}
