// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Genuine CI CLI (`genuineci sync secrets`)

import 'dart:io';

/// Provides type-safe access to Genuine CI secrets via environment variables.
abstract final class Secrets {
  const Secrets._();

  /// Secret key: `FIREBASE_TOKEN`
  static String get firebaseToken =>
      Platform.environment['FIREBASE_TOKEN'] ??
      (throw StateError('Secret "FIREBASE_TOKEN" is not set in environment.'));

}
