name: lume_dart
description: Dart bindings for Lume CLI macOS VMs.
version: 1.0.0
repository: https://github.com/openci-org/openci/tree/develop/packages/lume_dart
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
