name: lume_dart
description: Dart bindings for Lume CLI macOS VMs.
version: 1.0.1
repository: https://github.com/openci-org/openci/tree/develop/packages/lume_dart
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.24.0


