name: avf_dart_example
description: An example usage of avf_dart to boot Linux in macOS Virtualization.framework.
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  avf_dart:
    path: ../
