name: build_job_planner
description: Planner for build jobs created from GitHub webhook events in OpenCI.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.5

resolution: workspace

dependencies:
  analyzer: ^10.0.1
  logging: ^1.2.0
  openci_shared: ^1.0.1
  sentry: ^9.22.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
