import 'dart:convert';
import 'dart:io';
import 'dart:isolate';

import 'package:genuineci_cli/src/commands/sync/generate_workspace_paths.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  group('generateWorkspacePathsSource', () {
    test('generates WorkspaceDirectory-compatible nodes and a leaf getter', () {
      final root = WorkspacePathNode('.', 'WorkspaceRoot');
      final apps = WorkspacePathNode('apps', r'WorkspaceRoot$Apps');
      root.children['apps'] = apps;
      apps.children['dashboard'] = WorkspacePathNode(
        'apps/dashboard',
        r'WorkspaceRoot$Apps$Dashboard',
      );

      expect(generateWorkspacePathsSource(root), r'''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by GenuineCI CLI (`genuineci sync --paths`)
// dart format off

import 'package:openci_workflow/openci_workflow.dart' show WorkspaceDirectory;

/// Paths relative to the repository root.
abstract final class WorkspacePaths {
  static const root = WorkspaceRoot._('.');
}

extension type const WorkspaceRoot._(String _path) implements WorkspaceDirectory {
  WorkspaceRoot$Apps get apps => const WorkspaceRoot$Apps._("apps");
}

extension type const WorkspaceRoot$Apps._(String _path) implements WorkspaceDirectory {
  WorkspaceDirectory get dashboard => const WorkspaceDirectory("apps/dashboard");
}
''');
    });
  });

  group('workspaceDirectoryNameToField', () {
    const cases = {
      'dashboard': 'dashboard',
      'build_job_worker': 'buildJobWorker',
      'openci': 'openci',
      'flutter_ci': 'flutterCI',
      'OpenCI': 'openCI',
      'CI_tools': 'ciTools',
      'ci': 'ci',
      'cicd_logs': 'cicdLogs',
      'my_cicd_logs': 'myCicdLogs',
      'circular_progress': 'circularProgress',
      'v2_api': 'v2Api',
      'build__job_worker': 'buildJobWorker',
      'my-app': 'myApp',
      'my app': 'myApp',
      '.ci': 'ci',
      'APIClient': 'apiClient',
      'alreadyCamelCase': 'alreadyCamelCase',
      'sync': 'sync',
      'switch': 'switch_',
      'class': 'class_',
      'null': 'null_',
      'async': 'async_',
      'await': 'await_',
      'hash_code': 'hashCode_',
      'to_string': 'toString_',
      'runtime_type': 'runtimeType_',
      'no_such_method': 'noSuchMethod_',
    };
    for (final entry in cases.entries) {
      test('converts ${entry.key} to ${entry.value}', () {
        expect(workspaceDirectoryNameToField(entry.key), entry.value);
      });
    }

    for (final name in ['', '___', '2dashboard']) {
      test('rejects unusable field name ${jsonEncode(name)}', () {
        expect(
          () => workspaceDirectoryNameToField(name),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              contains(jsonEncode(name)),
            ),
          ),
        );
      });
    }
  });

  group('validateWorkspacePath', () {
    for (final path in [
      'apps/dashboard',
      'packages/my app',
      '.',
      './apps/app',
    ]) {
      test('accepts repository-relative path $path', () {
        expect(() => validateWorkspacePath(path), returnsNormally);
      });
    }

    for (final path in [
      '',
      '/tmp/workspace/apps/dashboard',
      'C:/workspace/apps/dashboard',
      r'C:\workspace\apps\dashboard',
      'C:apps/dashboard',
      r'\\server\share\dashboard',
      r'\apps\dashboard',
      '../dashboard',
      'apps/../dashboard',
      r'apps\..\dashboard',
      'apps/\u0000dashboard',
    ]) {
      test('rejects invalid path ${jsonEncode(path)}', () {
        expect(
          () => validateWorkspacePath(path),
          throwsA(
            isA<FormatException>().having(
              (error) => error.message,
              'message',
              contains(jsonEncode(path)),
            ),
          ),
        );
      });
    }
  });

  group('buildWorkspacePathTree', () {
    test('preserves directory levels and shares their intermediate nodes', () {
      final root = buildWorkspacePathTree([
        'apps/dashboard',
        'apps/build_job_worker',
        'packages/openci_workflow',
        'openci',
      ]);

      expect(root.path, '.');
      expect(root.children.keys, ['apps', 'openci', 'packages']);
      final apps = root.children['apps']!;
      expect(apps.path, 'apps');
      expect(apps.children.keys, ['buildJobWorker', 'dashboard']);
      expect(apps.children['dashboard']!.path, 'apps/dashboard');
      expect(root.children['openci']!.path, 'openci');
      expect(
        root.children['packages']!.children['openciWorkflow']!.path,
        'packages/openci_workflow',
      );
    });

    test('rejects sibling name collisions before generating source', () {
      expect(
        () => buildWorkspacePathTree(['apps/build-job', 'apps/build_job']),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            allOf(
              contains('"apps/build-job"'),
              contains('"apps/build_job"'),
              contains('both map to "buildJob"'),
            ),
          ),
        ),
      );
    });

    test('allows matching getters in different parent directories', () {
      final root = buildWorkspacePathTree(['apps/my-app', 'packages/my_app']);

      expect(root.children['apps']!.children['myApp']!.path, 'apps/my-app');
      expect(
        root.children['packages']!.children['myApp']!.path,
        'packages/my_app',
      );
    });

    test('rejects sibling collisions after escaping reserved names', () {
      expect(
        () => buildWorkspacePathTree(['apps/switch', 'apps/switch_']),
        throwsA(
          isA<FormatException>().having(
            (error) => error.message,
            'message',
            allOf(
              contains('"apps/switch"'),
              contains('"apps/switch_"'),
              contains('both map to "switch_"'),
            ),
          ),
        ),
      );
    });
  });

  group('generateWorkspacePaths', () {
    test('normalizes, sorts and deduplicates equivalent workspace paths', () {
      final first = generateWorkspacePaths([
        './packages/openci_workflow/',
        'apps//dashboard',
        r'apps\dashboard',
        'apps/./dashboard',
        '.',
        'apps',
      ]);
      final second = generateWorkspacePaths([
        'apps/dashboard',
        'packages/openci_workflow',
      ]);

      expect(first, second);
    });

    test('validates directory names and paths before generating source', () {
      expect(
        () => generateWorkspacePaths(['apps/2dashboard']),
        throwsFormatException,
      );
      expect(
        () => generateWorkspacePaths(['/tmp/workspace']),
        throwsFormatException,
      );
    });
  });

  group('generated Dart code', () {
    late Directory directory;
    late File definitions;
    late File probe;
    late String packageConfigPath;

    setUpAll(() async {
      final packageConfig = await Isolate.packageConfig;
      if (packageConfig == null) {
        throw StateError('Cannot find the test package configuration');
      }
      packageConfigPath = File.fromUri(packageConfig).path;
    });

    setUp(() async {
      directory = await Directory.systemTemp.createTemp('openci-path-code-');
      definitions = File(p.join(directory.path, 'paths.g.dart'));
      probe = File(p.join(directory.path, 'probe.dart'));
    });

    tearDown(() => directory.delete(recursive: true));

    Future<ProcessResult> runProbe({String? workingDirectory}) => Process.run(
      Platform.resolvedExecutable,
      ['--packages=$packageConfigPath', probe.path],
      workingDirectory: workingDirectory,
      environment: {'PATH': Platform.environment['PATH']!},
      includeParentEnvironment: false,
    );

    test(
      'passes root, parents and leaves as directories and returns String paths',
      () async {
        await definitions.writeAsString(
          generateWorkspacePaths([
            'apps',
            'apps/dashboard',
            'apps/dashboard/android/app/src/main',
            'apps/build_job_worker',
            'apps/openci_cli/lib/src/commands/sync',
            'packages/openci_workflow',
            'openci/workflows',
            'ci/tools',
            'ci_tools/scripts',
            'foo_bar/package',
            'foo/bar/package',
            'length',
            'is_empty',
          ]),
        );
        await probe.writeAsString('''
import 'dart:convert';
import 'package:openci_workflow/openci_workflow.dart';
import 'paths.g.dart';

String acceptPath(WorkspaceDirectory path) => path;

void main() {
  final WorkspaceRoot\$Openci openci = WorkspacePaths.root.openci;
  final WorkspaceRoot\$CI ci = WorkspacePaths.root.ci;
  final WorkspaceRoot\$CITools ciTools = WorkspacePaths.root.ciTools;
  print(jsonEncode([
    acceptPath(WorkspacePaths.root),
    acceptPath(WorkspacePaths.root.apps),
    acceptPath(WorkspacePaths.root.apps.dashboard),
    acceptPath(WorkspacePaths.root.apps.dashboard.android.app),
    acceptPath(WorkspacePaths.root.apps.dashboard.android.app.src.main),
    acceptPath(WorkspacePaths.root.apps.buildJobWorker),
    acceptPath(WorkspacePaths.root.apps.openciCli.lib.src.commands.sync),
    acceptPath(WorkspacePaths.root.packages.openciWorkflow),
    acceptPath(openci),
    acceptPath(openci.workflows),
    acceptPath(ci.tools),
    acceptPath(ciTools.scripts),
    acceptPath(WorkspacePaths.root.fooBar.package),
    acceptPath(WorkspacePaths.root.foo.bar.package),
    acceptPath(WorkspacePaths.root.length),
    acceptPath(WorkspacePaths.root.isEmpty),
  ]));
}
''');

        final result = await runProbe();

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(jsonDecode(result.stdout as String), [
          '.',
          'apps',
          'apps/dashboard',
          'apps/dashboard/android/app',
          'apps/dashboard/android/app/src/main',
          'apps/build_job_worker',
          'apps/openci_cli/lib/src/commands/sync',
          'packages/openci_workflow',
          'openci',
          'openci/workflows',
          'ci/tools',
          'ci_tools/scripts',
          'foo_bar/package',
          'foo/bar/package',
          'length',
          'is_empty',
        ]);
      },
    );

    test(
      'reserved getters compile and preserve their directory paths',
      () async {
        const paths = [
          'switch/team',
          'class/null',
          'async/await',
          'to_string/hash_code',
          'runtime_type/no_such_method',
        ];
        await definitions.writeAsString(generateWorkspacePaths(paths));
        await probe.writeAsString('''
import 'dart:convert';
import 'package:openci_workflow/openci_workflow.dart';
import 'paths.g.dart';

String acceptPath(WorkspaceDirectory path) => path;

void main() {
  print(jsonEncode([
    acceptPath(WorkspacePaths.root.switch_.team),
    acceptPath(WorkspacePaths.root.class_.null_),
    acceptPath(WorkspacePaths.root.async_.await_),
    acceptPath(WorkspacePaths.root.toString_.hashCode_),
    acceptPath(WorkspacePaths.root.runtimeType_.noSuchMethod_),
  ]));
}
''');

        final result = await runProbe();

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(jsonDecode(result.stdout as String), paths);
      },
    );

    test(
      'preserves quotes and interpolation characters in directory paths',
      () async {
        const path =
            r'''apps/$team/${member}/"quoted"/single'quote'''
            '\n\t';
        await definitions.writeAsString(generateWorkspacePaths([path]));
        await probe.writeAsString('''
import 'dart:convert';
import 'paths.g.dart';

void main() {
  print(jsonEncode(WorkspacePaths.root.apps.team.member.quoted.singleQuote));
}
''');

        final result = await runProbe();

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(jsonDecode(result.stdout as String), path);
      },
    );

    test('resolves relative paths from each checkout', () async {
      await definitions.writeAsString(
        generateWorkspacePaths(['apps/dashboard']),
      );
      await probe.writeAsString('''
import 'dart:io';
import 'paths.g.dart';

void main() {
  print(File(WorkspacePaths.root.apps.dashboard + '/marker.txt').readAsStringSync());
}
''');

      for (final checkout in ['first', 'second']) {
        final root = p.join(directory.path, checkout);
        final marker = File(p.join(root, 'apps', 'dashboard', 'marker.txt'));
        await marker.parent.create(recursive: true);
        await marker.writeAsString(checkout);

        final result = await runProbe(workingDirectory: root);

        expect(result.exitCode, 0, reason: result.stderr.toString());
        expect(result.stdout, '$checkout\n');
      }
    });

    test('an empty workspace still provides its root as a String', () async {
      await definitions.writeAsString(generateWorkspacePaths([]));
      await probe.writeAsString('''
import 'paths.g.dart';

void main() {
  final String path = WorkspacePaths.root;
  print(path);
}
''');

      final result = await runProbe();

      expect(result.exitCode, 0, reason: result.stderr.toString());
      expect(result.stdout, '.\n');
    });
  });
}
