/// {@template secrets_code_generator}
/// Generates type-safe Dart code for accessing Genuine CI secrets.
/// {@endtemplate}
class SecretsCodeGenerator {
  /// {@macro secrets_code_generator}
  const SecretsCodeGenerator();

  static const _reservedKeywords = {
    'abstract', 'as', 'assert', 'async', 'await', 'base', 'break', 'case',
    'catch', 'class', 'const', 'continue', 'covariant', 'default', 'deferred',
    'do', 'dynamic', 'else', 'enum', 'export', 'extends', 'extension',
    'external', 'factory', 'false', 'final', 'finally', 'for', 'Function',
    'get', 'hide', 'if', 'implements', 'import', 'in', 'interface', 'is',
    'late', 'library', 'mixin', 'new', 'null', 'of', 'on', 'operator', 'part',
    'required', 'rethrow', 'return', 'sealed', 'set', 'show', 'static',
    'super', 'switch', 'sync', 'this', 'throw', 'true', 'try', 'type',
    'typedef', 'var', 'void', 'when', 'while', 'with', 'yield',
  };

  /// Converts a secret name (e.g. `SLACK_WEBHOOK_URL` or `app-store-key`)
  /// into a valid camelCase Dart identifier.
  static String toCamelCase(String input) {
    final cleaned = input.trim();
    if (cleaned.isEmpty) return 'empty';

    final parts = cleaned
        .split(RegExp('[^a-zA-Z0-9]+'))
        .where((p) => p.isNotEmpty)
        .toList();

    if (parts.isEmpty) return 'secret';

    final buffer = StringBuffer();
    for (var i = 0; i < parts.length; i++) {
      final part = parts[i];
      if (i == 0) {
        buffer.write(part.toLowerCase());
      } else {
        if (part.length == 1) {
          buffer.write(part.toUpperCase());
        } else {
          buffer.write(part[0].toUpperCase() + part.substring(1).toLowerCase());
        }
      }
    }

    var result = buffer.toString();

    if (RegExp('^[0-9]').hasMatch(result)) {
      result = 's$result';
    }

    if (_reservedKeywords.contains(result)) {
      result = '${result}_';
    }

    return result;
  }

  /// Generates the contents of `secrets.g.dart` from a list of secret names.
  String generate(List<String> rawSecretNames) {
    final uniqueNames = rawSecretNames.toSet().toList()..sort();

    final buffer = StringBuffer()
      ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
      ..writeln('// Generated by Genuine CI CLI (`genuineci sync secrets`)')
      ..writeln()
      ..writeln("import 'dart:io';")
      ..writeln()
      ..writeln(
        '/// Provides type-safe access to Genuine CI secrets via environment '
        'variables.',
      )
      ..writeln('abstract final class Secrets {')
      ..writeln('  const Secrets._();')
      ..writeln();

    if (uniqueNames.isEmpty) {
      buffer.writeln('  // No secrets registered yet.');
    } else {
      final usedPropertyNames = <String>{};

      for (final rawName in uniqueNames) {
        var propName = toCamelCase(rawName);
        if (usedPropertyNames.contains(propName)) {
          var counter = 2;
          while (usedPropertyNames.contains('${propName}_$counter')) {
            counter++;
          }
          propName = '${propName}_$counter';
        }
        usedPropertyNames.add(propName);

        final escapedRawName =
            rawName.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

        buffer
          ..writeln('  /// Secret key: `$escapedRawName`')
          ..writeln('  static String get $propName =>')
          ..writeln("      Platform.environment['$escapedRawName'] ??")
          ..writeln(
            '      (throw StateError("Secret \'$escapedRawName\' is not set in '
            'environment."));',
          )
          ..writeln();
      }
    }

    buffer.writeln('}');
    return buffer.toString();
  }
}
