// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class MacosUpdaterApiPigeonCodecReader: FlutterStandardReader {
}

private class MacosUpdaterApiPigeonCodecWriter: FlutterStandardWriter {
}

private class MacosUpdaterApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MacosUpdaterApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MacosUpdaterApiPigeonCodecWriter(data: data)
  }
}

class MacosUpdaterApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MacosUpdaterApiPigeonCodec(readerWriter: MacosUpdaterApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MacosUpdaterHostApi {
  func setFeedUrl(url: String) throws
  func checkForUpdates() throws
  func setScheduledCheckInterval(seconds: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MacosUpdaterHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MacosUpdaterApiPigeonCodec.shared }
  /// Sets up an instance of `MacosUpdaterHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MacosUpdaterHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setFeedUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.macos_updater.MacosUpdaterHostApi.setFeedUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFeedUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        do {
          try api.setFeedUrl(url: urlArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFeedUrlChannel.setMessageHandler(nil)
    }
    let checkForUpdatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.macos_updater.MacosUpdaterHostApi.checkForUpdates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkForUpdatesChannel.setMessageHandler { _, reply in
        do {
          try api.checkForUpdates()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      checkForUpdatesChannel.setMessageHandler(nil)
    }
    let setScheduledCheckIntervalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.macos_updater.MacosUpdaterHostApi.setScheduledCheckInterval\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScheduledCheckIntervalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secondsArg = args[0] as! Int64
        do {
          try api.setScheduledCheckInterval(seconds: secondsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScheduledCheckIntervalChannel.setMessageHandler(nil)
    }
  }
}
