name: openci_worker_cli
description: OpenCI Worker CLI
version: 0.6.5
repository: https://github.com/open-ci-io/openci

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  args: ^2.7.0
  dart_firebase_admin: ^0.4.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.6.0
  process_run: ^1.2.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  openci_worker: openci_worker_cli
