// Mocks generated by Mockito 5.4.6 from annotations
// in openci_server/test/storage_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i9;

import 'package:minio/src/minio.dart' as _i7;
import 'package:minio/src/minio_models.dart' as _i4;
import 'package:minio/src/minio_models_generated.dart' as _i2;
import 'package:minio/src/minio_poller.dart' as _i5;
import 'package:minio/src/minio_stream.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCopyObjectResult_0 extends _i1.SmartFake
    implements _i2.CopyObjectResult {
  _FakeCopyObjectResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationConfiguration_1 extends _i1.SmartFake
    implements _i2.NotificationConfiguration {
  _FakeNotificationConfiguration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMinioByteStream_2 extends _i1.SmartFake
    implements _i3.MinioByteStream {
  _FakeMinioByteStream_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListMultipartUploadsOutput_3 extends _i1.SmartFake
    implements _i4.ListMultipartUploadsOutput {
  _FakeListMultipartUploadsOutput_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationPoller_4 extends _i1.SmartFake
    implements _i5.NotificationPoller {
  _FakeNotificationPoller_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListObjectsResult_5 extends _i1.SmartFake
    implements _i4.ListObjectsResult {
  _FakeListObjectsResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListObjectsOutput_6 extends _i1.SmartFake
    implements _i4.ListObjectsOutput {
  _FakeListObjectsOutput_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListObjectsV2Output_7 extends _i1.SmartFake
    implements _i4.ListObjectsV2Output {
  _FakeListObjectsV2Output_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListPartsOutput_8 extends _i1.SmartFake
    implements _i4.ListPartsOutput {
  _FakeListPartsOutput_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostPolicyResult_9 extends _i1.SmartFake
    implements _i4.PostPolicyResult {
  _FakePostPolicyResult_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccessControlPolicy_10 extends _i1.SmartFake
    implements _i2.AccessControlPolicy {
  _FakeAccessControlPolicy_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatObjectResult_11 extends _i1.SmartFake
    implements _i4.StatObjectResult {
  _FakeStatObjectResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSubscription_12<T> extends _i1.SmartFake
    implements _i6.StreamSubscription<T> {
  _FakeStreamSubscription_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_13<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Minio].
///
/// See the documentation for Mockito's code generation for more information.
class MockMinio extends _i1.Mock implements _i7.Minio {
  MockMinio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get partSize =>
      (super.noSuchMethod(Invocation.getter(#partSize), returnValue: 0) as int);

  @override
  int get maximumPartSize =>
      (super.noSuchMethod(Invocation.getter(#maximumPartSize), returnValue: 0)
          as int);

  @override
  int get maxObjectSize =>
      (super.noSuchMethod(Invocation.getter(#maxObjectSize), returnValue: 0)
          as int);

  @override
  String get endPoint =>
      (super.noSuchMethod(
            Invocation.getter(#endPoint),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#endPoint),
            ),
          )
          as String);

  @override
  int get port =>
      (super.noSuchMethod(Invocation.getter(#port), returnValue: 0) as int);

  @override
  bool get useSSL =>
      (super.noSuchMethod(Invocation.getter(#useSSL), returnValue: false)
          as bool);

  @override
  String get accessKey =>
      (super.noSuchMethod(
            Invocation.getter(#accessKey),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#accessKey),
            ),
          )
          as String);

  @override
  String get secretKey =>
      (super.noSuchMethod(
            Invocation.getter(#secretKey),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#secretKey),
            ),
          )
          as String);

  @override
  bool get enableTrace =>
      (super.noSuchMethod(Invocation.getter(#enableTrace), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> bucketExists(String? bucket) =>
      (super.noSuchMethod(
            Invocation.method(#bucketExists, [bucket]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String> completeMultipartUpload(
    String? bucket,
    String? object,
    String? uploadId,
    List<_i2.CompletedPart>? parts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeMultipartUpload, [
              bucket,
              object,
              uploadId,
              parts,
            ]),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#completeMultipartUpload, [
                  bucket,
                  object,
                  uploadId,
                  parts,
                ]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i2.CopyObjectResult> copyObject(
    String? bucket,
    String? object,
    String? srcObject, [
    _i4.CopyConditions? conditions,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#copyObject, [
              bucket,
              object,
              srcObject,
              conditions,
            ]),
            returnValue: _i6.Future<_i2.CopyObjectResult>.value(
              _FakeCopyObjectResult_0(
                this,
                Invocation.method(#copyObject, [
                  bucket,
                  object,
                  srcObject,
                  conditions,
                ]),
              ),
            ),
          )
          as _i6.Future<_i2.CopyObjectResult>);

  @override
  _i6.Future<String?> findUploadId(String? bucket, String? object) =>
      (super.noSuchMethod(
            Invocation.method(#findUploadId, [bucket, object]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i2.NotificationConfiguration> getBucketNotification(
    String? bucket,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBucketNotification, [bucket]),
            returnValue: _i6.Future<_i2.NotificationConfiguration>.value(
              _FakeNotificationConfiguration_1(
                this,
                Invocation.method(#getBucketNotification, [bucket]),
              ),
            ),
          )
          as _i6.Future<_i2.NotificationConfiguration>);

  @override
  _i6.Future<Map<String, dynamic>?> getBucketPolicy(dynamic bucket) =>
      (super.noSuchMethod(
            Invocation.method(#getBucketPolicy, [bucket]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<String> getBucketRegion(String? bucket) =>
      (super.noSuchMethod(
            Invocation.method(#getBucketRegion, [bucket]),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getBucketRegion, [bucket]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i3.MinioByteStream> getObject(String? bucket, String? object) =>
      (super.noSuchMethod(
            Invocation.method(#getObject, [bucket, object]),
            returnValue: _i6.Future<_i3.MinioByteStream>.value(
              _FakeMinioByteStream_2(
                this,
                Invocation.method(#getObject, [bucket, object]),
              ),
            ),
          )
          as _i6.Future<_i3.MinioByteStream>);

  @override
  _i6.Future<_i3.MinioByteStream> getPartialObject(
    String? bucket,
    String? object, [
    int? offset,
    int? length,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getPartialObject, [
              bucket,
              object,
              offset,
              length,
            ]),
            returnValue: _i6.Future<_i3.MinioByteStream>.value(
              _FakeMinioByteStream_2(
                this,
                Invocation.method(#getPartialObject, [
                  bucket,
                  object,
                  offset,
                  length,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.MinioByteStream>);

  @override
  _i6.Future<String> initiateNewMultipartUpload(
    String? bucket,
    String? object,
    Map<String, String>? metaData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#initiateNewMultipartUpload, [
              bucket,
              object,
              metaData,
            ]),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#initiateNewMultipartUpload, [
                  bucket,
                  object,
                  metaData,
                ]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Stream<_i4.IncompleteUpload> listIncompleteUploads(
    String? bucket,
    String? prefix, [
    bool? recursive = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#listIncompleteUploads, [
              bucket,
              prefix,
              recursive,
            ]),
            returnValue: _i6.Stream<_i4.IncompleteUpload>.empty(),
          )
          as _i6.Stream<_i4.IncompleteUpload>);

  @override
  _i6.Future<_i4.ListMultipartUploadsOutput> listIncompleteUploadsQuery(
    String? bucket,
    String? prefix,
    String? keyMarker,
    String? uploadIdMarker,
    String? delimiter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listIncompleteUploadsQuery, [
              bucket,
              prefix,
              keyMarker,
              uploadIdMarker,
              delimiter,
            ]),
            returnValue: _i6.Future<_i4.ListMultipartUploadsOutput>.value(
              _FakeListMultipartUploadsOutput_3(
                this,
                Invocation.method(#listIncompleteUploadsQuery, [
                  bucket,
                  prefix,
                  keyMarker,
                  uploadIdMarker,
                  delimiter,
                ]),
              ),
            ),
          )
          as _i6.Future<_i4.ListMultipartUploadsOutput>);

  @override
  _i5.NotificationPoller listenBucketNotification(
    String? bucket, {
    String? prefix,
    String? suffix,
    List<String>? events,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listenBucketNotification,
              [bucket],
              {#prefix: prefix, #suffix: suffix, #events: events},
            ),
            returnValue: _FakeNotificationPoller_4(
              this,
              Invocation.method(
                #listenBucketNotification,
                [bucket],
                {#prefix: prefix, #suffix: suffix, #events: events},
              ),
            ),
          )
          as _i5.NotificationPoller);

  @override
  _i6.Future<List<_i2.Bucket>> listBuckets() =>
      (super.noSuchMethod(
            Invocation.method(#listBuckets, []),
            returnValue: _i6.Future<List<_i2.Bucket>>.value(<_i2.Bucket>[]),
          )
          as _i6.Future<List<_i2.Bucket>>);

  @override
  _i6.Stream<_i4.ListObjectsResult> listObjects(
    String? bucket, {
    String? prefix = '',
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listObjects,
              [bucket],
              {#prefix: prefix, #recursive: recursive},
            ),
            returnValue: _i6.Stream<_i4.ListObjectsResult>.empty(),
          )
          as _i6.Stream<_i4.ListObjectsResult>);

  @override
  _i6.Future<_i4.ListObjectsResult> listAllObjects(
    String? bucket, {
    String? prefix = '',
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listAllObjects,
              [bucket],
              {#prefix: prefix, #recursive: recursive},
            ),
            returnValue: _i6.Future<_i4.ListObjectsResult>.value(
              _FakeListObjectsResult_5(
                this,
                Invocation.method(
                  #listAllObjects,
                  [bucket],
                  {#prefix: prefix, #recursive: recursive},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.ListObjectsResult>);

  @override
  _i6.Future<_i4.ListObjectsOutput> listObjectsQuery(
    String? bucket,
    String? prefix,
    String? marker,
    String? delimiter,
    int? maxKeys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listObjectsQuery, [
              bucket,
              prefix,
              marker,
              delimiter,
              maxKeys,
            ]),
            returnValue: _i6.Future<_i4.ListObjectsOutput>.value(
              _FakeListObjectsOutput_6(
                this,
                Invocation.method(#listObjectsQuery, [
                  bucket,
                  prefix,
                  marker,
                  delimiter,
                  maxKeys,
                ]),
              ),
            ),
          )
          as _i6.Future<_i4.ListObjectsOutput>);

  @override
  _i6.Stream<_i4.ListObjectsResult> listObjectsV2(
    String? bucket, {
    String? prefix = '',
    bool? recursive = false,
    String? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listObjectsV2,
              [bucket],
              {#prefix: prefix, #recursive: recursive, #startAfter: startAfter},
            ),
            returnValue: _i6.Stream<_i4.ListObjectsResult>.empty(),
          )
          as _i6.Stream<_i4.ListObjectsResult>);

  @override
  _i6.Future<_i4.ListObjectsResult> listAllObjectsV2(
    String? bucket, {
    String? prefix = '',
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listAllObjectsV2,
              [bucket],
              {#prefix: prefix, #recursive: recursive},
            ),
            returnValue: _i6.Future<_i4.ListObjectsResult>.value(
              _FakeListObjectsResult_5(
                this,
                Invocation.method(
                  #listAllObjectsV2,
                  [bucket],
                  {#prefix: prefix, #recursive: recursive},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.ListObjectsResult>);

  @override
  _i6.Future<_i4.ListObjectsV2Output> listObjectsV2Query(
    String? bucket,
    String? prefix,
    String? continuationToken,
    String? delimiter,
    int? maxKeys,
    String? startAfter,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listObjectsV2Query, [
              bucket,
              prefix,
              continuationToken,
              delimiter,
              maxKeys,
              startAfter,
            ]),
            returnValue: _i6.Future<_i4.ListObjectsV2Output>.value(
              _FakeListObjectsV2Output_7(
                this,
                Invocation.method(#listObjectsV2Query, [
                  bucket,
                  prefix,
                  continuationToken,
                  delimiter,
                  maxKeys,
                  startAfter,
                ]),
              ),
            ),
          )
          as _i6.Future<_i4.ListObjectsV2Output>);

  @override
  _i6.Stream<_i2.Part> listParts(
    String? bucket,
    String? object,
    String? uploadId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listParts, [bucket, object, uploadId]),
            returnValue: _i6.Stream<_i2.Part>.empty(),
          )
          as _i6.Stream<_i2.Part>);

  @override
  _i6.Future<_i4.ListPartsOutput> listPartsQuery(
    String? bucket,
    String? object,
    String? uploadId,
    int? marker,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listPartsQuery, [
              bucket,
              object,
              uploadId,
              marker,
            ]),
            returnValue: _i6.Future<_i4.ListPartsOutput>.value(
              _FakeListPartsOutput_8(
                this,
                Invocation.method(#listPartsQuery, [
                  bucket,
                  object,
                  uploadId,
                  marker,
                ]),
              ),
            ),
          )
          as _i6.Future<_i4.ListPartsOutput>);

  @override
  _i6.Future<void> makeBucket(String? bucket, [String? region]) =>
      (super.noSuchMethod(
            Invocation.method(#makeBucket, [bucket, region]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> presignedGetObject(
    String? bucket,
    String? object, {
    int? expires,
    Map<String, String>? respHeaders,
    DateTime? requestDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #presignedGetObject,
              [bucket, object],
              {
                #expires: expires,
                #respHeaders: respHeaders,
                #requestDate: requestDate,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #presignedGetObject,
                  [bucket, object],
                  {
                    #expires: expires,
                    #respHeaders: respHeaders,
                    #requestDate: requestDate,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i4.PostPolicyResult> presignedPostPolicy(
    _i4.PostPolicy? postPolicy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#presignedPostPolicy, [postPolicy]),
            returnValue: _i6.Future<_i4.PostPolicyResult>.value(
              _FakePostPolicyResult_9(
                this,
                Invocation.method(#presignedPostPolicy, [postPolicy]),
              ),
            ),
          )
          as _i6.Future<_i4.PostPolicyResult>);

  @override
  _i6.Future<String> presignedPutObject(
    String? bucket,
    String? object, {
    int? expires,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #presignedPutObject,
              [bucket, object],
              {#expires: expires},
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #presignedPutObject,
                  [bucket, object],
                  {#expires: expires},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> presignedUrl(
    String? method,
    String? bucket,
    String? object, {
    int? expires,
    String? resource,
    Map<String, String>? reqParams,
    DateTime? requestDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #presignedUrl,
              [method, bucket, object],
              {
                #expires: expires,
                #resource: resource,
                #reqParams: reqParams,
                #requestDate: requestDate,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #presignedUrl,
                  [method, bucket, object],
                  {
                    #expires: expires,
                    #resource: resource,
                    #reqParams: reqParams,
                    #requestDate: requestDate,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> putObject(
    String? bucket,
    String? object,
    _i6.Stream<_i9.Uint8List>? data, {
    int? size,
    int? chunkSize,
    Map<String, String>? metadata,
    void Function(int)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putObject,
              [bucket, object, data],
              {
                #size: size,
                #chunkSize: chunkSize,
                #metadata: metadata,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #putObject,
                  [bucket, object, data],
                  {
                    #size: size,
                    #chunkSize: chunkSize,
                    #metadata: metadata,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> removeAllBucketNotification(String? bucket) =>
      (super.noSuchMethod(
            Invocation.method(#removeAllBucketNotification, [bucket]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeBucket(String? bucket) =>
      (super.noSuchMethod(
            Invocation.method(#removeBucket, [bucket]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeIncompleteUpload(String? bucket, String? object) =>
      (super.noSuchMethod(
            Invocation.method(#removeIncompleteUpload, [bucket, object]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeObject(String? bucket, String? object) =>
      (super.noSuchMethod(
            Invocation.method(#removeObject, [bucket, object]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeObjects(String? bucket, List<String>? objects) =>
      (super.noSuchMethod(
            Invocation.method(#removeObjects, [bucket, objects]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setBucketNotification(
    String? bucket,
    _i2.NotificationConfiguration? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setBucketNotification, [bucket, config]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setBucketPolicy(
    String? bucket, [
    Map<String, dynamic>? policy,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#setBucketPolicy, [bucket, policy]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setObjectACL(
    String? bucket,
    String? object,
    String? policy,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setObjectACL, [bucket, object, policy]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.AccessControlPolicy> getObjectACL(
    String? bucket,
    String? object,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getObjectACL, [bucket, object]),
            returnValue: _i6.Future<_i2.AccessControlPolicy>.value(
              _FakeAccessControlPolicy_10(
                this,
                Invocation.method(#getObjectACL, [bucket, object]),
              ),
            ),
          )
          as _i6.Future<_i2.AccessControlPolicy>);

  @override
  _i6.Future<_i4.StatObjectResult> statObject(
    String? bucket,
    String? object, {
    bool? retrieveAcls = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #statObject,
              [bucket, object],
              {#retrieveAcls: retrieveAcls},
            ),
            returnValue: _i6.Future<_i4.StatObjectResult>.value(
              _FakeStatObjectResult_11(
                this,
                Invocation.method(
                  #statObject,
                  [bucket, object],
                  {#retrieveAcls: retrieveAcls},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.StatObjectResult>);
}

/// A class which mocks [MinioByteStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockMinioByteStream extends _i1.Mock implements _i3.MinioByteStream {
  MockMinioByteStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(Invocation.getter(#isBroadcast), returnValue: false)
          as bool);

  @override
  _i6.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<int>> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<int>> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<int>> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Stream<List<int>> asBroadcastStream({
    void Function(_i6.StreamSubscription<List<int>>)? onListen,
    void Function(_i6.StreamSubscription<List<int>>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asBroadcastStream, [], {
              #onListen: onListen,
              #onCancel: onCancel,
            }),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.StreamSubscription<List<int>> listen(
    void Function(List<int>)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_12<List<int>>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i6.StreamSubscription<List<int>>);

  @override
  _i6.Stream<List<int>> where(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<S> map<S>(S Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#map, [convert]),
            returnValue: _i6.Stream<S>.empty(),
          )
          as _i6.Stream<S>);

  @override
  _i6.Stream<E> asyncMap<E>(_i6.FutureOr<E> Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [convert]),
            returnValue: _i6.Stream<E>.empty(),
          )
          as _i6.Stream<E>);

  @override
  _i6.Stream<E> asyncExpand<E>(_i6.Stream<E>? Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncExpand, [convert]),
            returnValue: _i6.Stream<E>.empty(),
          )
          as _i6.Stream<E>);

  @override
  _i6.Stream<List<int>> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [onError], {#test: test}),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<S> expand<S>(Iterable<S> Function(List<int>)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [convert]),
            returnValue: _i6.Stream<S>.empty(),
          )
          as _i6.Stream<S>);

  @override
  _i6.Future<dynamic> pipe(_i6.StreamConsumer<List<int>>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(#pipe, [streamConsumer]),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Stream<S> transform<S>(
    _i6.StreamTransformer<List<int>, S>? streamTransformer,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [streamTransformer]),
            returnValue: _i6.Stream<S>.empty(),
          )
          as _i6.Stream<S>);

  @override
  _i6.Future<List<int>> reduce(
    List<int> Function(List<int>, List<int>)? combine,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<S> fold<S>(S? initialValue, S Function(S, List<int>)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i6.Future<S>.value(v),
                ) ??
                _FakeFuture_13<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
          )
          as _i6.Future<S>);

  @override
  _i6.Future<String> join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [needle]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> forEach(void Function(List<int>)? action) =>
      (super.noSuchMethod(
            Invocation.method(#forEach, [action]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> every(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#every, [test]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> any(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#any, [test]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<R> cast<R>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _i6.Stream<R>.empty(),
          )
          as _i6.Stream<R>);

  @override
  _i6.Future<List<List<int>>> toList() =>
      (super.noSuchMethod(
            Invocation.method(#toList, []),
            returnValue: _i6.Future<List<List<int>>>.value(<List<int>>[]),
          )
          as _i6.Future<List<List<int>>>);

  @override
  _i6.Future<Set<List<int>>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: _i6.Future<Set<List<int>>>.value(<List<int>>{}),
          )
          as _i6.Future<Set<List<int>>>);

  @override
  _i6.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#drain, [futureValue]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i6.Future<E>.value(v),
                ) ??
                _FakeFuture_13<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
          )
          as _i6.Future<E>);

  @override
  _i6.Stream<List<int>> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<List<int>> takeWhile(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<List<int>> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<List<int>> skipWhile(bool Function(List<int>)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Stream<List<int>> distinct([
    bool Function(List<int>, List<int>)? equals,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#distinct, [equals]),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i6.Future<List<int>> firstWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<int>> lastWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<int>> singleWhere(
    bool Function(List<int>)? test, {
    List<int> Function()? orElse,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<int>> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Stream<List<int>> timeout(
    Duration? timeLimit, {
    void Function(_i6.EventSink<List<int>>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);
}
