name: landing_page
description: OpenCI, Inc. landing page
version: 0.0.1

environment:
  sdk: 3.11.5

resolution: workspace

dependencies:
  jaspr: ^0.23.0
  jaspr_content: ^0.5.2

dev_dependencies:
  build_runner: ^2.14.0
  build_web_compilers: ^4.4.17
  jaspr_builder: ^0.23.0
  lints: ^6.0.0

jaspr:
  mode: static
