export const secretsCollection = 'secrets_v0'
export const workflowsCollection = 'workflows_v1'
export const workflowTemplatesCollection = 'workflow_templates_v0'
export const buildJobsCollection = 'build_jobs_v0'
export const teamsCollection = 'teams_v0'
export const usersCollection = 'users_v0'
export const environmentVariablesCollection = 'environment_variables_v0'

export const callableFunctionPath = 'createSecretV1'
export const updateSecretCallableFunctionPath = 'updateSecretV1'
