name: avf_cli
description: CLI tool for managing Apple Virtualization.framework macOS VMs, powered by avf_dart.
version: 0.1.8

repository: https://github.com/openci-org/openci/tree/main/packages/avf_cli
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  args: ^2.5.0
  avf_dart: ^0.1.22
  cli_util: ^0.4.1
  hooks: ^2.0.0
  path: ^1.9.0
  pubspec_version_hook: ^0.1.0

executables:
  avf: avf
