name: CI for LP

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci_lp:
    name: CI for LP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./openci_runner/lp
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Prepare Dependencies
        run: pnpm install

      - name: Prettier Check
        run: pnpm prettier --check .

      - name: ESLint Check
        run: pnpm run lint -- --max-warnings 0
