name: genuineci_cli CI

on:
  pull_request:
    paths:
      - "apps/genuineci_cli/**"
      - "packages/openci_shared/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/genuineci-cli-ci.yml"

  push:
    branches:
      - develop
      - main
    paths:
      - "apps/genuineci_cli/**"
      - "packages/openci_shared/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - ".github/workflows/genuineci-cli-ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies (Workspace root)
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed apps/genuineci_cli

      - name: Analyze code
        run: flutter analyze apps/genuineci_cli

      - name: Run unit tests
        working-directory: apps/genuineci_cli
        run: flutter test
